### ISSUE TITLE
[diagramme] Resource

### ISSUE THREAD

**Issue by qcoumes** [PremierLangage/platon-conception#127]

**Comment by nimdanor** [comment]
Je pense qu'il faut que l'on ai en lien entre la ressource et l'asset ,
que la ressource connaisse les assets qui l'instancie et que les assets connaisse la version de la ressource et les versions des sous-ressources utilisés  pour les construire.

**Comment by nimdanor** [comment]
IL n'y pas de méthode "Instancier/new"  qui transforme la ressource en asset dans le diagramme actuel.
IL faut une méthode "publish" qui fait passer la ressource de ressource privé à ressource publique (ce qui a lien quand une ressource est instanciée et quand un membre publie la ressource.

**Comment by nimdanor** [comment]
Doublons avec la #117.
