### ISSUE TITLE
[Utilisateur]:connection-lti

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/platon-conception#22]
Le cas d'utilisation [connection-lti](http://github.com/plgitlogin/platon-conception/edit/master/UC/Utilisateur/connection-lti.md)

**Comment by plgitlogin** [comment]
Peut tu indiquer parmi  les données fournies par le LMS.
Les quelles on a, les quelles on veut.

**Comment by qcoumes** [comment]
Fait @plgitlogin @nimdanor .
