### ISSUE TITLE
[Administrateur]:aav-add-ressource

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/platon-conception#6]
Le cas d'utilisation [aav-add-ressource](http://github.com/plgitlogin/platon-conception/edit/master/UC/Administrateur/aav-add-ressource.md)

**Comment by nimdanor** [comment]
wrong issue see [aav-add-ressource](http://github.com/plgitlogin/platon-conception/edit/master/UC/Membre/aav-add-ressource.md)
